# Generated by Django 3.1.5 on 2021-02-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0003_auto_20210202_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressao',
            name='data_final',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='progressao',
            name='data_inicio',
            field=models.DateField(),
        ),
    ]
