# Generated by Django 3.1.5 on 2021-02-03 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0004_auto_20210202_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progressao',
            name='data_final',
            field=models.DateField(verbose_name='Data final'),
        ),
        migrations.AlterField(
            model_name='progressao',
            name='data_inicio',
            field=models.DateField(verbose_name='Data de inicio'),
        ),
    ]
