# Generated by Django 3.1.5 on 2021-02-06 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0005_auto_20210202_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comprovante',
            name='arquivo',
            field=models.FileField(upload_to='pdf/', verbose_name='Arquivo'),
        ),
    ]
