# Generated by Django 3.1.5 on 2021-02-07 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0006_auto_20210206_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campus',
            name='telefone',
            field=models.IntegerField(verbose_name='Telefone'),
        ),
    ]
